sudo: required
dist: trusty

language: php

branches:
  only:
    - master
  except:
    - development

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql
  - redis
  - memcached

addons:
  mariadb: '10.0'
  
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  # Create DB for testing.
  - mysql -u root -e 'CREATE DATABASE shieldon_unittest;'
  - mysql -u root -e "CREATE USER 'shieldon'@'localhost' IDENTIFIED BY 'taiwan';"
  - mysql -u root -e "GRANT ALL ON shieldon_unittest.* TO 'shieldon'@'localhost';"
  - sudo apt-get update
  - sudo apt-get install -y php-apcu
  - sudo apt-get install -y php-apcu-bc
  - sudo apt-get install -y php$(phpenv version-name)-memcache
  - sudo apt-get install -y php$(phpenv version-name)-memcached
  - sudo apt-get install -y php$(phpenv version-name)-redis

script: composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)