sudo: required
dist: trusty

language: php

branches:
  only:
    - master
  except:
    - development

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql
  - redis
  - memcached

addons:
  mariadb: '10.0'
  
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  # Create DB for testing.
  - mysql -u root -e 'CREATE DATABASE shieldon_unittest;'
  - mysql -u root -e "CREATE USER 'shieldon'@'localhost' IDENTIFIED BY 'taiwan';"
  - mysql -u root -e "GRANT ALL ON shieldon_unittest.* TO 'shieldon'@'localhost';"
  - pecl channel-update pecl.php.net
  - pecl install -f apcu
  - pecl install -f apcu_bc
  - pecl install -f memcache
  - pecl install -f memcachd
  - echo "extension=apcu_bc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)