sudo: required
dist: trusty

language: php

branches:
  only:
    - master
  except:
    - development

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql
  - redis
  - memcached

addons:
  mariadb: '10.0'
  
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  # Create DB for testing.
  - mysql -u root -e 'CREATE DATABASE shieldon_unittest;'
  - mysql -u root -e "CREATE USER 'shieldon'@'localhost' IDENTIFIED BY 'taiwan';"
  - mysql -u root -e "GRANT ALL ON shieldon_unittest.* TO 'shieldon'@'localhost';"
  - pecl channel-update pecl.php.net
  - printf "\n" | pecl install -f apcu
  - printf "\n" | pecl install -f apcu_bc
  - printf "\n" | pecl install -f memcache
  - printf "\n" | pecl install -f memcachd
  - printf "\n" | pecl install -f redis

script: composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)